import json
import os
import sys
from datetime import datetime
from pathlib import Path

# ==========================================
# 🏗️ Core Logic: Manual Generator (v1.1)
# ==========================================
# 職責：通用 DCS 數位孿生手冊生成器。將精煉後的智慧 JSON 轉化為 Markdown 資產。
# 語義：建立可供 RAG 檢索的結構化工程文檔。
# ==========================================

try:
    from .utils import IDStandardizer
except ImportError:
    # 支援直接執行測試
    sys.path.append(os.path.abspath(os.path.dirname(__file__)))
    from utils import IDStandardizer

class ManualGenerator:
    """
    將精煉後的智慧 JSON 轉化為 Markdown 資產。
    """
    def __init__(self, client: str, factory: str, plant: str):
        # ==========================================
        # 🗺️ Initialization & Context Context
        # ==========================================
        self.client = client
        self.factory = factory
        self.plant = plant
        self.timestamp = datetime.now().strftime("%Y-%m-%d")

    def generate(self, intel_report_path: str, output_path: str):
        # ==========================================
        # 📂 Document Generation Pipeline
        # ==========================================
        if not os.path.exists(intel_report_path):
            print(f"Error: Intel report not found at {intel_report_path}")
            return

        with open(intel_report_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        meta = data.get("metadata", {})
        tag = meta.get("TAG", self.plant)
        service = meta.get("SERVICE", "Unit Control")

        # 使用標準化位號作為 ID
        std_id = IDStandardizer.standardize(tag, plant=self.plant)
        ssot_id = f"DCS-{std_id}-{self.factory.upper()}"
        
        lines = []
        lines.append("---")
        lines.append(f"id: {ssot_id}")
        lines.append(f"kb_id: {std_id}")
        lines.append(f"physical_id: {self.plant}")
        lines.append(f"plant: {self.plant}")
        lines.append(f"tags: [{self.client}, {self.factory}, {self.plant}, Digital_Twin, Intelligence]")
        lines.append("status: standardized")
        lines.append(f"last_sync: {self.timestamp}")
        lines.append("---\n")
        
        lines.append(f"# {self.plant} {service} 智慧解析手冊 (RAG-Optimized)\n")
        lines.append("## 📋 設備概覽")
        lines.append(f"- **單元編號**: {tag}")
        lines.append(f"- **服務名稱**: {service}")
        lines.append(f"- **描述**: {self.plant} 核心控制單元，包含 SEQ 與 DDC 邏輯整合.\n")

        lines.append("## 🎯 關鍵控制路徑 (Control Path)")
        lines.append("| 控制項 | 端子地址 | 語義描述 | 關鍵步驟/階段 |")
        lines.append("| :--- | :--- | :--- | :--- |")
        
        for item in data.get("pattern", [])[:15]:
            out_addr = item.get("OUTADDR")
            out_desc = item.get("OUT_DESC", out_addr)
            ranges = [s.get("range") for s in item.get("active_states", [])]
            range_str = ", ".join(ranges[:3]) + ("..." if len(ranges) > 3 else "")
            lines.append(f"| Output | `{out_addr}` | {out_desc} | Step {range_str} |")

        lines.append("\n## ⏲️ 製程階段 (Process Phases)")
        lines.append("| 階段名稱 | 起始步 | 結束步 |")
        lines.append("| :--- | :--- | :--- |")
        for proc in data.get('process_timer', [])[:15]:
            lines.append(f"| {proc.get('BPROCNAME')} | {proc.get('S')} | {proc.get('E')} |")

        lines.append(f"\n---\n*Last Updated: {self.timestamp} | Generated by Conductor Orchestrator*")

        # ==========================================
        # 💾 Persistence
        # ==========================================
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        
        print(f"Manual successfully generated: {output_path}")

if __name__ == "__main__":
    # --- 🤝 Orchestration Placeholder ---
    pass
